cursor #a9b1d6
cursor_text_color #c0caf5

foreground            #a9b1d6
background            #101014
selection_foreground  #101014
selection_background  #f92aad
url_color             #58c7e0

color0   #16161e
color1   #ff548e
color2   #58e065
color3   #fff354
color4   #39b8d4
color5   #005467
color6   #58c7e0
color7   #dae8eb
color8   #848f91
color9   #ff8ab2
color10  #92ff9d
color11  #fff792
color12  #77dff6
color13  #92ebff
color14  #b9f2ff
color15  #f7fdff
